name: "bookstore"
services:
  product-db:
    image: postgres:17.2-alpine
    container_name: product-db
    environment:
      - POSTGRES_USER=my_root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  order-db:
    image: postgres:17.2-alpine
    container_name: order-db
    environment:
      - POSTGRES_USER=my_root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=my_root
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m