spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:my_root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    open-in-view: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:my_root}
    password: ${SPRING_RABBITMQ_PASSWORD:123456}
server:
  port: 8082
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
orders:
  order-events-exchange: order-events-exchange
  new-orders-queue: new-orders-queue
  delivered-orders-queue: delivered-orders-queue
  cancelled-orders-queue: cancelled-orders-queue
  error-orders-queue: error-orders-queue