name: Product Service

on:
  push:
    paths:
      - services/product-service/**
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-product-service:latest
      working-directory: ./services/product-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Build with gradle
        run: ./gradlew build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build Docker Image
        run: ./gradlew bootBuildImage

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Publish Docker Image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}